/**
 * FlowModel -> Playwright script exporter (spec 5.5).
 *
 * The generated script is standalone: it requires only `playwright` plus a local
 * Chromium build. Mapping rules:
 * - `env` / `secret` variables become `process.env` lookups with optional default.
 * - `input` variables read `ROBO_<LABEL>` and fall back to their declared default.
 * - `{{var}}` interpolation becomes a `vars[...]` lookup inside a template literal.
 * - `SelectorSpec.candidates` becomes a `firstMatch()` helper tried in order.
 * - `manual` steps throw a descriptive error (or `page.pause()` with `pauseOnManual`).
 */
import type { Condition, FlowModel, SelectorSpec, Step, VariableDef } from '../flow/schema.js';
import { ExportError } from '../errors.js';

/** Options for {@link exportPlaywright}. */
export interface ExportOptions {
  /** Launch with a visible window and slight slow-down (debugging). */
  headed?: boolean;
  /** Indentation width (default 2). */
  indent?: number;
  /** Use `page.pause()` before `manual` steps so a human can attach. */
  pauseOnManual?: boolean;
  /** Emit CommonJS (`require`) or ESM (`import`) boilerplate. */
  module?: 'cjs' | 'esm';
  /**
   * Directory the flow was loaded from. Relative `goto` URLs resolve against it
   * (mirroring `core/flow/url.ts`) so the generated script runs from anywhere.
   */
  flowDir?: string;
}

const HELPERS = `// --- generated helpers -------------------------------------------------------
/**
 * Resolve the first selector candidate that matches, mirroring the engine's
 * SelectorSpec semantics (candidates are tried in order).
 */
async function firstMatch(page, candidates) {
  for (const candidate of candidates) {
    const locator = page.locator(candidate);
    if ((await locator.count()) > 0) return locator.first();
  }
  throw new Error('No selector candidate matched: ' + JSON.stringify(candidates));
}

/**
 * Bridge Playwright's event-based downloads to the flow's "waitForDownload
 * step" semantics. Downloads are queued as soon as they are emitted, so the
 * triggering click may appear either before or after the wait step.
 */
/**
 * Resolve a flow-authored URL exactly like the engine does.
 *
 * Absolute URLs (http:, https:, file:, data:, about:, ...) pass through.
 * A leading "/" is a file-system absolute path. Anything else is resolved
 * against ROBO_FLOW_DIR (default: the current working directory) and converted
 * to a file:// URL, mirroring core/flow/url.ts.
 */
function resolveFlowUrl(url) {
  const raw = String(url);
  if (/^[a-zA-Z][a-zA-Z0-9+.-]*:/.test(raw)) return raw;
  const path = require('node:path');
  const base = process.env.ROBO_FLOW_DIR || __ROBO_FLOW_DIR__ || process.cwd();
  const absolute = path.isAbsolute(raw) ? raw : path.resolve(base, raw);
  return require('node:url').pathToFileURL(absolute).href;
}

function createDownloadQueue(page) {
  const queue = [];
  const waiters = [];
  page.on('download', (download) => {
    if (waiters.length > 0) waiters.shift()(download);
    else queue.push(download);
  });
  return async function nextDownload() {
    if (queue.length > 0) return queue.shift();
    return new Promise((resolve) => waiters.push(resolve));
  };
}
// -----------------------------------------------------------------------------`;

/**
 * Convert a flow into a runnable Playwright script.
 *
 * @param flow - Validated FlowModel.
 * @param options - Emission options.
 * @returns Standalone script source (CommonJS by default).
 */
export function exportPlaywright(flow: FlowModel, options: ExportOptions = {}): string {
  return new PlaywrightEmitter(flow, options).render();
}

class PlaywrightEmitter {
  private readonly lines: string[] = [];
  private readonly indentUnit: string;
  private readonly moduleKind: 'cjs' | 'esm';

  public constructor(
    private readonly flow: FlowModel,
    private readonly options: ExportOptions,
  ) {
    this.indentUnit = ' '.repeat(options.indent ?? 2);
    this.moduleKind = options.module ?? 'cjs';
  }

  public render(): string {
    this.header();
    this.variables();
    this.push(HELPERS);
    this.push('');
    this.main();
    // Bake the flow's directory into the resolver so the script runs from any cwd.
    const baked = JSON.stringify(this.options.flowDir ?? null);
    return `${this.lines.join('\n').replaceAll('__ROBO_FLOW_DIR__', baked)}\n`;
  }

  private push(line = ''): void {
    this.lines.push(line);
  }

  private pad(depth: number): string {
    return this.indentUnit.repeat(depth);
  }

  private header(): void {
    this.push('// AUTO-GENERATED by RoboBrowser from a FlowModel. Do not edit by hand.');
    this.push(`// Flow: ${this.flow.name} (${this.flow.id})`);
    this.push('// Run with: node this-script.js');
    if (this.moduleKind === 'esm') {
      this.push("import { chromium } from 'playwright';");
      this.push("import path from 'node:path';");
    } else {
      this.push("const { chromium } = require('playwright');");
      this.push("const path = require('node:path');");
    }
    this.push('');
  }

  private variables(): void {
    const defs = Object.entries(this.flow.variables ?? {});
    if (defs.length === 0) {
      this.push('const vars = {};');
      this.push('');
      return;
    }
    this.push('const vars = {');
    for (const [name, def] of defs) {
      this.push(`${this.indentUnit}${quoteKey(name)}: ${renderVariable(name, def)},`);
    }
    this.push('};');
    this.push('');
  }

  private main(): void {
    const headless = this.options.headed ? 'false' : 'true';
    const slowMo = this.options.headed ? ', slowMo: 100' : '';
    this.push('(async () => {');
    // Honour CHROME_PATH like the rest of the stack: on a machine without
    // Playwright's downloaded browser this is what makes the script runnable
    // against the system Chromium/Chrome.
    this.push(`${this.pad(1)}const executablePath = process.env.CHROME_PATH || undefined;`);
    this.push(
      `${this.pad(1)}const browser = await chromium.launch({ headless: ${headless}${slowMo}, ...(executablePath ? { executablePath } : {}) });`,
    );
    this.push(`${this.pad(1)}const context = await browser.newContext({ acceptDownloads: true });`);
    this.push(`${this.pad(1)}const page = await context.newPage();`);
    this.push(`${this.pad(1)}const artifacts = [];`);
    this.push(`${this.pad(1)}const outDir = process.env.ROBO_OUT || process.cwd();`);
    this.push(`${this.pad(1)}const nextDownload = createDownloadQueue(page);`);
    this.push('');
    this.emitSteps(this.flow.steps, 1);
    this.push(`${this.pad(1)}await browser.close();`);
    this.push(
      `${this.pad(1)}console.log(JSON.stringify({ status: 'ok', variables: vars, artifacts }, null, 2));`,
    );
    this.push('})().catch((error) => {');
    this.push(`${this.pad(1)}console.error(error);`);
    this.push(`${this.pad(1)}process.exit(1);`);
    this.push('});');
  }

  private emitSteps(steps: readonly Step[], depth: number): void {
    for (const step of steps) this.emitStep(step, depth);
  }

  private emitStep(step: Step, depth: number): void {
    const pad = this.pad(depth);
    this.push(`${pad}// ${step.id}: ${step.type}`);
    switch (step.type) {
      case 'goto':
        this.push(
          `${pad}await page.goto(resolveFlowUrl(${tpl(step.url)}), { waitUntil: ${JSON.stringify(
            step.waitUntil === 'domcontentloaded' ? 'domcontentloaded' : 'load',
          )} });`,
        );
        break;

      case 'click': {
        const opts: string[] = [];
        if (step.button && step.button !== 'left')
          opts.push(`button: ${JSON.stringify(step.button)}`);
        if (step.clickCount && step.clickCount !== 1) opts.push(`clickCount: ${step.clickCount}`);
        const arg = opts.length > 0 ? `, { ${opts.join(', ')} }` : '';
        this.push(`${pad}await ${locatorExpr(step.selector)}.click(${arg.replace(/^, /, '')});`);
        break;
      }

      case 'type':
        if (step.clear !== false && step.delayMs === undefined) {
          this.push(`${pad}await ${locatorExpr(step.selector)}.fill(${tpl(step.value)});`);
        } else {
          this.push(`${pad}await ${locatorExpr(step.selector)}.click();`);
          if (step.clear !== false)
            this.push(`${pad}await ${locatorExpr(step.selector)}.fill('');`);
          const delay = step.delayMs !== undefined ? `, { delay: ${step.delayMs} }` : '';
          this.push(
            `${pad}await ${locatorExpr(step.selector)}.pressSequentially(${tpl(step.value)}${delay});`,
          );
        }
        if (step.submit) this.push(`${pad}await page.keyboard.press('Enter');`);
        break;

      case 'select':
        this.push(`${pad}await ${locatorExpr(step.selector)}.selectOption(${tpl(step.value)});`);
        break;

      case 'hover':
        this.push(`${pad}await ${locatorExpr(step.selector)}.hover();`);
        break;

      case 'scroll':
        if (step.selector) {
          this.push(`${pad}await ${locatorExpr(step.selector)}.scrollIntoViewIfNeeded();`);
        } else {
          this.push(`${pad}await page.mouse.wheel(${step.x ?? 0}, ${step.y ?? 0});`);
        }
        break;

      case 'waitForPage':
        // Page fingerprints reference a host-side registry; Playwright has no
        // equivalent, so wait for the load event and leave a TODO comment.
        this.push(`${pad}await page.waitForLoadState('load');`);
        this.push(
          `${pad}// TODO: page fingerprint "${step.target}" — add an explicit wait if needed.`,
        );
        break;

      case 'waitForSelector': {
        const state = step.state ?? 'visible';
        const timeout = step.timeout !== undefined ? `, timeout: ${step.timeout}` : '';
        this.push(
          `${pad}await ${locatorExpr(step.selector)}.waitFor({ state: ${JSON.stringify(state)}${timeout} });`,
        );
        break;
      }

      case 'waitForUrl':
        this.push(`${pad}await page.waitForURL(${renderUrlMatcher(step.pattern)});`);
        break;

      case 'waitForNetworkIdle':
        this.push(`${pad}await page.waitForLoadState('networkidle');`);
        break;

      case 'waitForDownload':
        this.push(`${pad}{`);
        this.push(`${pad}${this.indentUnit}const download = await nextDownload();`);
        this.push(
          `${pad}${this.indentUnit}const target = path.join(outDir, download.suggestedFilename());`,
        );
        this.push(`${pad}${this.indentUnit}await download.saveAs(target);`);
        this.push(`${pad}${this.indentUnit}artifacts.push(target);`);
        this.push(`${pad}}`);
        break;

      case 'extract': {
        const locator = locatorExpr(step.selector);
        const target = `vars[${JSON.stringify(step.into)}]`;
        if (step.all) {
          const body = step.attr
            ? `(el) => el.getAttribute(${JSON.stringify(step.attr)})`
            : `(el) => el.innerText`;
          this.push(`${pad}${target} = await ${locator}.evaluateAll((els) => els.map(${body}));`);
        } else {
          const reader = step.attr ? `getAttribute(${JSON.stringify(step.attr)})` : 'innerText()';
          this.push(`${pad}${target} = await ${locator}.${reader};`);
        }
        this.push(`${pad}console.log(${JSON.stringify(`extracted ${step.into}:`)}, ${target});`);
        break;
      }

      case 'screenshot':
        this.push(`${pad}{`);
        this.push(
          `${pad}${this.indentUnit}const target = ${
            step.saveTo
              ? tpl(step.saveTo)
              : `path.join(outDir, ${JSON.stringify(`${step.id}.png`)})`
          };`,
        );
        this.push(
          `${pad}${this.indentUnit}await page.screenshot({ path: target, fullPage: ${step.fullPage ? 'true' : 'false'} });`,
        );
        this.push(`${pad}${this.indentUnit}artifacts.push(target);`);
        this.push(`${pad}}`);
        break;

      case 'branch':
        this.push(`${pad}if (${renderCondition(step.condition)}) {`);
        this.emitSteps(step.then, depth + 1);
        if (step.else && step.else.length > 0) {
          this.push(`${pad}} else {`);
          this.emitSteps(step.else, depth + 1);
        }
        this.push(`${pad}}`);
        break;

      case 'loop':
        this.push(`${pad}{`);
        this.push(`${pad}${this.indentUnit}const items = ${renderLoopItems(step)};`);
        this.push(`${pad}${this.indentUnit}for (let i = 0; i < items.length; i += 1) {`);
        this.push(
          `${pad}${this.indentUnit}${this.indentUnit}vars[${JSON.stringify(step.as)}] = items[i];`,
        );
        this.emitSteps(step.steps, depth + 2);
        this.push(`${pad}${this.indentUnit}}`);
        this.push(`${pad}}`);
        break;

      case 'setVar':
        this.push(`${pad}vars[${JSON.stringify(step.name)}] = ${renderValue(step.value)};`);
        break;

      case 'httpCall':
        this.push(`${pad}{`);
        this.push(`${pad}${this.indentUnit}const res = await fetch(${tpl(step.url)}, {`);
        this.push(
          `${pad}${this.indentUnit}${this.indentUnit}method: ${JSON.stringify(step.method.toUpperCase())},`,
        );
        if (step.headers) {
          this.push(
            `${pad}${this.indentUnit}${this.indentUnit}headers: ${renderValue(step.headers)},`,
          );
        }
        if (step.body !== undefined) {
          this.push(
            `${pad}${this.indentUnit}${this.indentUnit}body: JSON.stringify(${renderValue(step.body)}),`,
          );
        }
        this.push(`${pad}${this.indentUnit}});`);
        this.push(`${pad}${this.indentUnit}if (!res.ok) throw new Error('HTTP ' + res.status);`);
        if (step.into) {
          this.push(
            `${pad}${this.indentUnit}vars[${JSON.stringify(step.into)}] = await res.json().catch(() => res.text());`,
          );
        }
        this.push(`${pad}}`);
        break;

      case 'manual':
        this.push(`${pad}{`);
        this.push(`${pad}${this.indentUnit}const message = ${JSON.stringify(step.message)};`);
        if (this.options.pauseOnManual) {
          this.push(`${pad}${this.indentUnit}console.warn('MANUAL (${step.reason}): ' + message);`);
          this.push(`${pad}${this.indentUnit}await page.pause();`);
        } else {
          this.push(
            `${pad}${this.indentUnit}if (vars.__manualAutoContinue !== true && process.env.ROBO_MANUAL_AUTOCONTINUE !== '1') {`,
          );
          this.push(
            `${pad}${this.indentUnit}${this.indentUnit}throw new Error('Manual step (${step.reason}) requires a human: ' + message +`,
          );
          this.push(
            `${pad}${this.indentUnit}${this.indentUnit}${this.indentUnit}'\\nRe-run with ROBO_MANUAL_AUTOCONTINUE=1 to skip this gate.');`,
          );
          this.push(`${pad}${this.indentUnit}}`);
        }
        this.push(`${pad}}`);
        break;

      default: {
        const exhaustive: never = step;
        throw new ExportError(
          `Unsupported step for Playwright export: ${JSON.stringify(exhaustive)}`,
        );
      }
    }
    this.push('');
  }
}

/* ---------------------------------------------------------------- rendering */

/** Build a locator expression, collapsing `candidates` into `firstMatch`. */
function locatorExpr(selector: SelectorSpec): string {
  if (typeof selector === 'string') return `page.locator(${JSON.stringify(selector)})`;
  if ('candidates' in selector) {
    const parts = selector.candidates.map((candidate) => candidateToExpression(candidate));
    return `(await firstMatch(page, [${parts.join(', ')}]))`;
  }
  return `page.locator(${JSON.stringify(candidateToPlaywrightSelector(selector))})`;
}

/** For `candidates`, each entry is either a plain string or a factory. */
function candidateToExpression(selector: SelectorSpec): string {
  const rendered = candidateToPlaywrightSelector(selector);
  return JSON.stringify(rendered);
}

/** Convert one SelectorSpec variant into a Playwright selector string. */
export function candidateToPlaywrightSelector(selector: SelectorSpec): string {
  if (typeof selector === 'string') return selector;
  if ('candidates' in selector) return candidateToPlaywrightSelector(selector.candidates[0]!);
  if ('testId' in selector) return `[data-testid="${escapeAttr(selector.testId)}"]`;
  if ('role' in selector) {
    return selector.name
      ? `role=${selector.role}[name="${escapeAttr(selector.name)}"]`
      : `role=${selector.role}`;
  }
  if ('text' in selector)
    return selector.exact ? `text="${selector.text}"` : `text=${selector.text}`;
  if ('css' in selector) return selector.css;
  if ('xpath' in selector) return `xpath=${selector.xpath}`;
  const exhaustive: never = selector;
  return String(exhaustive);
}

/** Interpolate `{{var}}` into a template literal referencing `vars`. */
function tpl(value: string): string {
  if (!value.includes('{{')) return JSON.stringify(value);
  const inner = value
    .split(/(\{\{\s*[A-Za-z0-9_.\-[\]$]+\s*\}\})/)
    .map((part) => {
      const match = /^\{\{\s*([A-Za-z0-9_.\-[\]$]+)\s*\}\}$/.exec(part);
      if (match) return `\${vars[${JSON.stringify(match[1])}]}`;
      return part.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
    })
    .join('');
  return `\`${inner}\``;
}

function renderUrlMatcher(pattern: string): string {
  if (pattern.startsWith('/') && pattern.lastIndexOf('/') > 0) {
    const end = pattern.lastIndexOf('/');
    return `new RegExp(${JSON.stringify(pattern.slice(1, end))}, ${JSON.stringify(pattern.slice(end + 1))})`;
  }
  if (pattern.includes('*')) {
    const escaped = pattern.replace(/[.+?^${}()|[\]\\]/g, '\\$&').replace(/\*/g, '.*');
    return `new RegExp(${JSON.stringify(`^${escaped}$`)})`;
  }
  return JSON.stringify(pattern);
}

/** Render a `Condition` as an awaitable boolean expression. */
function renderCondition(condition: Condition): string {
  if ('pageIs' in condition) {
    return `true /* pageIs: "${condition.pageIs}" — fingerprints are host-side; adjust as needed */`;
  }
  if ('varEquals' in condition) {
    const name = JSON.stringify(condition.varEquals.name);
    const expected = JSON.stringify(condition.varEquals.value);
    return `JSON.stringify(vars[${name}]) === ${JSON.stringify(expected)}`;
  }
  if ('selectorExists' in condition) {
    return `(await ${locatorExpr(condition.selectorExists)}.count()) > 0`;
  }
  if ('not' in condition) return `!(${renderCondition(condition.not)})`;
  if ('all' in condition) {
    const parts = condition.all.map((c) => `(${renderCondition(c)})`);
    return parts.length > 0 ? parts.join(' && ') : 'true';
  }
  if ('any' in condition) {
    const parts = condition.any.map((c) => `(${renderCondition(c)})`);
    return parts.length > 0 ? parts.join(' || ') : 'false';
  }
  const exhaustive: never = condition;
  return String(exhaustive);
}

function renderLoopItems(step: Extract<Step, { type: 'loop' }>): string {
  if (Array.isArray(step.items)) return renderValue(step.items);
  if (step.items.includes('{{')) return tpl(step.items);
  return `vars[${JSON.stringify(step.items)}] ?? []`;
}

function renderValue(value: unknown): string {
  return JSON.stringify(value) ?? 'undefined';
}

function renderVariable(name: string, def: VariableDef): string {
  switch (def.type) {
    case 'const':
      return JSON.stringify(def.value) ?? 'undefined';
    case 'env':
    case 'secret':
      return def.default !== undefined
        ? `process.env[${JSON.stringify(def.key)}] ?? ${JSON.stringify(def.default)}`
        : `process.env[${JSON.stringify(def.key)}]`;
    case 'input': {
      const envKey = `ROBO_${name.toUpperCase().replace(/\W+/g, '_')}`;
      return def.default !== undefined
        ? `process.env[${JSON.stringify(envKey)}] ?? ${JSON.stringify(def.default)}`
        : `process.env[${JSON.stringify(envKey)}] ?? ''`;
    }
    default: {
      const exhaustive: never = def;
      return String(exhaustive);
    }
  }
}

function quoteKey(key: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key) ? key : JSON.stringify(key);
}

function escapeAttr(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}
